# Generated by Django 5.2.8 on 2025-11-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webhooks", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="webhookdelivery",
            options={"ordering": ("-triggered_at",)},
        ),
        migrations.AddIndex(
            model_name="webhook",
            index=models.Index(
                fields=["event", "is_enabled"], name="webhooks_we_event_4d0b93_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webhook",
            index=models.Index(
                fields=["created_at"], name="webhooks_we_created_9104e4_idx"
            ),
        ),
    ]
